### PR TITLE
uncouple from mB

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
Ok, migrations are working! They keep the old table names and use them! Yeah!
Tests are still very broken and js as well (I just left it in the app-folders).

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
well, found that error, have a new one, will go on tomorrow!

**Comment by fuzzylogic2000** [comment]
current status: worked inbeteween (even one of the travis checks). But I broke it again with the document migrations. Maybe we should just really migrate the data? or get this finally working!!!

**Comment by fuzzylogic2000** [comment]
@MagdaN @phillimorland @treba123 
it's working! Could you all test that on your local dbs?
I don't get why the travis pr is still failing. It seems to be all fine locally.

**Comment by treba123** [comment]
Nice work! Haven't yet had a deeper look, but it works on my local DB, tomorrow I can test it on a production DB if you want. For the polylint-error, see https://github.com/liqd/a4-product/pull/592

**Comment by MagdaN** [comment]
So, the migrations went through, but I think there is a problem with the phase types, e.g. I got an key error 'meinberlin_mapideas:collect'

**Comment by fuzzylogic2000** [comment]
@MagdaN Now it's working! :)

**Comment by MagdaN** [comment]
@fuzzylogic2000 its working indeed!

**Pull request merged**
