### PR TITLE
templates/error pages: do not show donation banner on error pages - f…

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
…ixes #1106

### CODE REVIEW

**Comment by rmader** [comment]
Why does speakup use the error template? Or why does this fix https://github.com/liqd/a4-product/issues/1107 ?

**Comment by fuzzylogic2000** [comment]
@rmader Upsi, it fixes #1106. How do I change the commit message again?

**Comment by fuzzylogic2000** [comment]
@rmader Alright, thanks, done!

**Comment by rmader** [comment]
LGTM!

**Pull request merged**
