### PR TITLE
2017 12 ka footer

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
Oh my, this could have be done much better. But this kind of looks like the design (apart from the ordering of the fields on mobile). I would like to be the one to rewrite and change it with the new design.

The class "navi" is only used in the footer (and also doesn't exist in mB), but the navi__list and __items are also used in the header.

### CODE REVIEW

**Comment by kleingeist** [comment]
on mobile the buttons are still side-by-side in the design
i think currently they are too prominent in mobile

**Comment by fuzzylogic2000** [comment]
Also, according to the design, the text should be between the impressum and the license links.

@rittermo It currently (in this branch) looks like follows. How much time should I invest to make it look like the current design and what exactly are the (most) important points?

screenshot from 2018-01-08 15-21-32
screenshot from 2018-01-08 15-20-37

**Comment by rittermo** [comment]
@fuzzylogic2000 This looks fine to me as it is. The only small thing would be that the blue boxes around the licences do not need to be full witdh on small screens, but rather inline with a little padding around them. Thank you!

**Comment by rittermo** [comment]
Oh and a tad more vertical space between the three links and the license links on small screens is neceassary (the same space as below the license links)

**Pull request merged**
